get 'redcase/index', :to => 'redcase#index'
get 'redcase/execlist', :to => 'redcase#execlist'
get 'redcase/test_suite_manager', :to => 'redcase#test_suite_manager'
get 'redcase/execution_suite_manager', :to => 'redcase#execution_suite_manager'
get 'redcase/reassign_test_case', :to => 'redcase#reassign_test_case'
get 'redcase/copy_test_case_to_exec', :to => 'redcase#copy_test_case_to_exec'
get 'redcase/delete_test_case_from_execution_suite', :to => 'redcase#delete_test_case_from_execution_suite'
get 'redcase/test_case_to_obsolete', :to => 'redcase#test_case_to_obsolete'
get 'redcase/get_test_case', :to => 'redcase#get_test_case'
get 'redcase/get_advanced_execution', :to => 'redcase#get_advanced_execution'
get 'redcase/execute', :to => 'redcase#execute'
get 'redcase/get_executions', :to => 'redcase#get_executions'
get 'redcase/get_attachment_urls', :to => 'redcase#get_attachment_urls'
get 'redcase/export_to_excel2', :to => 'redcase#export_to_excel2'
get 'redcase/export_to_rtf', :to => 'redcase#export_to_rtf'
get 'redcase/update_environment', :to => 'redcase#update_environment'
get 'redcase/update_exelists', :to => 'redcase#update_exelists'
get 'redcase/update_exelists2', :to => 'redcase#update_exelists2'
get 'redcase/graph', :to => 'redcase#graph'
get 'redcase/get_graph', :to => 'redcase#get_graph'
get 'redcase/update_combos', :to => 'redcase#update_combos'
get 'redcase/update_combos2', :to => 'redcase#update_combos2'

put 'redcase/update', :to => 'redcase#update'
match ':controller(/:action(/:id))(.:format)'